### ISSUE TITLE
WAMimeType no longer recognizes application/x-javascript as not binary

### ISSUE THREAD

**Issue by svenvc** [SeasideSt/Seaside#1203] opened 2020-06-07 13:36 UTC
https://github.com/SeasideSt/Seaside/commit/78d465878c7ce2839e368efecb4d615b6c6fb005#diff-1a9680844bf1a1cae49e853111e97092

did a useful cleanup/change, however it also (indadvertedly) change the

```
(WAMimeType main: 'application' sub: 'x-javascript') isBinary. 
```

from true to false.

**Comment by svenvc** [comment] 2020-06-07 13:37
My original problem report:

Hi,

I finally figured out a subtle but very annoying issue that I had, which comes down to a change in WAMimeType.

```
"pharo 7"

'application/javascript' asZnMimeType isBinary.
"false"
'application/x-javascript' asZnMimeType isBinary.
"false"

"older github://SeasideSt/Seaside:master/repository"
(WAMimeType main: 'application' sub: 'javascript') isBinary.
"true"
(WAMimeType main: 'application' sub: 'x-javascript') isBinary. 
"false"

"newer github://SeasideSt/Seaside:master/repository"
(WAMimeType main: 'application' sub: 'javascript') isBinary.
"false"
(WAMimeType main: 'application' sub: 'x-javascript') isBinary. 
"true"
```

As you can see the tests are reversed in the later Seaside (which was a diff between my development and deployment image).

This lead to a failure in serving .js files as needed for Bootstrap

I had to change/override 
```
jsbootstrapminJs
	^ WAFileLibraryResource
		filepath: 'js/bootstrap.min.js'
		mimeType: (WAMimeType main: 'application' sub: 'x-javascript')
		cacheDuration: (Duration days: 0 hours: 0 minutes: 30 seconds: 0)
		contents: (GRDelayedSend receiver: self selector: #jsbootstrapminJsContent)
```
to
```
jsbootstrapminJs
	^ WAFileLibraryResource
		filepath: 'js/bootstrap.min.js'
		mimeType: (WAMimeType main: 'application' sub: 'javascript')
		cacheDuration: (Duration days: 0 hours: 0 minutes: 30 seconds: 0)
		contents: (GRDelayedSend receiver: self selector: #jsbootstrapminJsContent)
```
Sven

**Comment by jbrichau** [comment] 2020-07-09 15:23
@svenvc thanks for reporting! The issue is fixed in the latest release.

**Closed** 2020-07-09 15:23 UTC

**Comment by svenvc** [comment] 2020-07-09 15:48
Thank you.
