### ISSUE TITLE
Warning when loading Seaside-Squeak-Core in Squeak 6.0beta: `BlockContext>>#renderOn:`

### ISSUE THREAD

**Issue by tcj** [SeasideSt/Seaside#1314] opened 2022-06-05 00:29 UTC
I think Squeak 6.0 retires `BlockContext` to go 100% `BlockClosure`.  So loading Seaside in 6.0beta is broken right now.  I can click "Proceed" to get past this loading error and onto the next one (will create another issue for that).

Loading BaselineOfSeaside3 -> Seaside-Squeak-Core results in Warning:
```
This package depends on the following classes:
  BlockContext
You must resolve these dependencies before you will be able to load these definitions: 
  BlockContext>>renderOn:
```

I don't know whether `BlockContext>>renderOn:` will need to be recreated for `BlockClosure`.  

I'm wondering if some possible fix will involve adjusting the baseline for Squeak to make choices for 6.0.

**Comment by theseion** [comment] 2022-06-06 06:36
Thanks for the report @tcj.
I'm closing this as duplicate of #1315, since solving #1315 will fix this issue automatically.

**Closed by theseion** 2022-06-06 06:36 UTC
