### ISSUE TITLE
GRPharoPlatform>>bindingOf: uses #name

### ISSUE THREAD

**Issue by macta** [SeasideSt/Seaside#986] opened 2018-05-04 08:33 UTC
When loading the PotsDam seaside tutorial it calls bindingOf: when loading and you get a pharo error:

#name called from GRPharoPlatform>>#bindingOf: has been deprecated.
Implement your own domain representation of an object, or use #asString or #printString instead.

Tiny fix I think - name is being given to the users...

**Comment by marschall** [comment] 2018-09-08 13:40
Can you provide more information:
- Which version of Seaside?
- Which Smalltalk dialect in which version?

**Comment by marschall** [comment] 2019-08-28 07:14
Closing because not enough information to reproduce was provided. Feel free to reopen with a way to reproduce.

**Closed by marschall** 2019-08-28 07:14 UTC
